# Generated by Django 4.1.1 on 2022-09-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('products_api', '0002_product_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='useraccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.useraccount'),
        ),
    ]
